#DB URL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Replace the dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Remove this line as H2 console is no longer needed
# spring.h2.console.enabled=true
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Github OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:replace-me}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:replace-me}
spring.security.oauth2.client.registration.github.redirect-uri=https://stubu.oks.de/api/auth/oauth2/github
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login

# PREVIEW OAuth2
spring.security.oauth2.client.registration.invite.client-id=${INVITE_CLIENT_ID:replace-me}
spring.security.oauth2.client.registration.invite.client-secret=${INVITE_CLIENT_SECRET:replace-me}
spring.security.oauth2.client.registration.invite.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.invite.redirect-uri=https://stubu.oks.de/auth-callback
spring.security.oauth2.client.provider.invite.authorization-uri=https://auth-preview.invite-toolcheck.de/oauth2/auth
spring.security.oauth2.client.provider.invite.token-uri=https://auth-preview.invite-toolcheck.de/oauth2/token

